### ISSUE TITLE
tracker: allow use in 48K model with external AY addons

### ISSUE THREAD

**Issue by jorgegv** [jorgegv/rage1#107]
There are apparently AY interfaces for 16K/48K models which are compatible with the one used in 128K models, so tracker music could be added to 48K builds. Currently, TRACKER feature depends on ZX_TARGET_128 feature, but it is a hardcoded dependency which may not be necessary.

Example AY interface: https://www.bytedelight.com/?product=zx-ay-external-stereo-audio-interface-for-all-zx-spectrum-models

Previous discussions on this issue were in  #103 .

Tasks:

- [ ] Move tracker code from `banked/128` to `banked/common` so that it can be compiled in 48K or 128K mode
- [ ] Move generated and tracker player code to `build/generated/banked/common`
- [ ] Remove hard dependency of TRACKER on ZX_TARGET_128
- [ ] Test in 48K mode with AY hardware available (may be a 128 running in 48K mode?)
- [ ] Document everything
